# Generated by Django 2.2 on 2022-11-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_base', '0002_auto_20221102_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='municipio',
        ),
    ]
