# Generated by Django 2.2 on 2022-11-02 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_base', '0003_remove_farm_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm_base.Owner'),
        ),
    ]
